const Action = {
  SET_SELECTED_GENRE: `SET_SELECTED_GENRE`,
  SET_CARDS_SHOWN_AMOUNT: `SET_CARDS_SHOWN_AMOUNT`,
  RESET_SHOWN_CARDS: `RESET_SHOWN_CARDS`,
  LOAD_MOVIES: `LOAD_MOVIES`,
  SET_REQUIRED_AUTHORIZATION: `SET_REQUIRED_AUTHORIZATION`,
  SAVE_USER_DATA: `SAVE_USER_DATA`,
  CHANGE_FAVORITE: `CHANGE_FAVORITE`,
  LOAD_PROMO: `LOAD_PROMO`,
  UPDATE_PROMO: `UPDATE_PROMO`,
  CHANGE_ACTIVE_STATUS: `CHANGE_ACTIVE_STATUS`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  CHANGE_SELECTED_MOVIE: `CHANGE_SELECTED_MOVIE`,
  BLOCK_FORM: `BLOCK_FORM`,
  CLEAN_FORM: `CLEAN_FORM`,
  LOAD_FAVORITE_MOVIES: `LOAD_FAVORITE_MOVIES`,
  ADD_TO_FAVORITE_MOVIES: `ADD_TO_FAVORITE_MOVIES`,
  DELETE_FROM_FAVORITE_MOVIES: `DELETE_FROM_FAVORITE_MOVIES`,
  UPLOAD_REVIEW: `UPLOAD_REVIEW`,
  SET_ERROR_LOGIN: `SET_ERROR_LOGIN`,
};

export default Action;
