const SET_SELECTED_GENRE = `SET_SELECTED_GENRE`;
const SET_CARDS_SHOWN_AMOUNT = `SET_CARDS_SHOWN_AMOUNT`;
const RESET_SHOWN_CARDS = `RESET_SHOWN_CARDS`;
const LOAD_MOVIES = `LOAD_MOVIES`;
const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
const SAVE_USER_DATA = `SAVE_USER_DATA`;

export {SET_SELECTED_GENRE, SET_CARDS_SHOWN_AMOUNT, RESET_SHOWN_CARDS, LOAD_MOVIES, REQUIRED_AUTHORIZATION, SAVE_USER_DATA};
