const SET_SELECTED_GENRE = `SET_SELECTED_GENRE`;
const SET_CARDS_SHOWN_AMOUNT = `SET_CARDS_SHOWN_AMOUNT`;
const RESET_SHOWN_CARDS = `RESET_SHOWN_CARDS`;
const LOAD_MOVIES = `LOAD_MOVIES`;
const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
const SAVE_USER_DATA = `SAVE_USER_DATA`;
const CHANGE_FAVORITE = `CHANGE_FAVORITE`;
const LOAD_PROMO = `LOAD_PROMO`;
const UPDATE_PROMO = `UPDATE_PROMO`;
const CHANGE_ACTIVE_STATUS = `CHANGE_ACTIVE_STATUS`;

export {SET_SELECTED_GENRE, SET_CARDS_SHOWN_AMOUNT, RESET_SHOWN_CARDS, LOAD_MOVIES,
  REQUIRED_AUTHORIZATION, SAVE_USER_DATA, CHANGE_FAVORITE,
  LOAD_PROMO, UPDATE_PROMO, CHANGE_ACTIVE_STATUS};
